---
- iptables:
    chain: "{{ item }}"
    policy: ACCEPT
  with_items: ["INPUT", "FORWARD", "OUTPUT"]

# Flush all
- iptables:
    chain: "{{ item }}"
    flush: yes
  with_items: ["INPUT", "OUTPUT"]

# Flush nat
- iptables:
   chain: "{{ item }}"
   flush: yes
   table: nat
  with_items: ["INPUT", "FORWARD", "OUTPUT"]

# Allow loopback
- iptables:
    action: append
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
    comment: Allow loopback
  
# Allow input
- iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    comment: Allow related and established connections

# PING
- iptables:
    chain: INPUT
    protocol: icmp
    jump: ACCEPT
    comment: Allow icmp Ping

# HTTP
- iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "80"
    jump: ACCEPT
    comment: Allow HTTP

# HTTPS
- iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "443"
    jump: ACCEPT
    comment: Allow HTTPS

# SSH
- iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "22"
    jump: ACCEPT
    comment: Allow SSH

# Drop others input
- iptables:
    chain: INPUT
    jump: DROP
    comment: Drop all
  notify:
      - persist iptables  

- name: Rules is set
  debug: 
    msg:
      - "Rules is set"
     