apiVersion: 1

deleteDatasources:
  - name: Prometheus

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://10.4.1.32:9090
    isDefault: true
    version: 1
    editable: true
