---
#- name: apt update
#  apt:
#    update_cache: yes

- name: Install prerequisites for Docker repository
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- name: add docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker apt repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
  
- name: install docker and it's dependencies
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: start and enable docker daemon
  service:
    name: docker
    state: started
    enabled: yes

- name: Check docker-compose file already exists.
  stat: path=/usr/bin/docker-compose
  register: docker_compose_file

- name: Install Docker-compose
  shell: curl -L "https://github.com/docker/compose/releases/download/v2.7.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose && ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
  become: true
  when: not docker_compose_file.stat.exists    

- name: Add the current user to docker group
  user: name=ubuntu append=yes groups=docker  